##
##
##

wandb:
  project: "test"
  entity: "visgator"
  save: false
  enabled: false
dataset:
  module: ".refcocog"
  path: "../refcocog"
  split_provider: "umd"
model:
  module: ".erpa"
  hidden_dim: 256
  encoders:
    model: "ViT-B-32" # default
    pretrained: "laion2b_s34b_b79k" # default
  detector:
    weights: "weights/groundingdino_swinb_cogcoor.pth"
    config: "config/GroundingDINO_SwinB_cfg.py"
    box_threshold: 0.35 # default
    text_threshold: 0.25 # default
  decoder:
    num_layers: 3
    num_heads: 8 # default
    epsilon_layer_scale: 0.1 # default
    dropout: 0.1 # default
  head:
    num_layers: 2
    num_heads: 8 # default
    dropout: 0.1 # default
  criterion:
    l1_weight: 1.0 # default
    giou_weight: 1.0 # default
seed: 42
compile: False
num_epochs: 3
train_batch_size: 8
eval_batch_size: 8
eval_interval: 2
optimizer:
  module: ".torch"
  name: "AdamW"
  args:
    lr: 0.001
lr_scheduler:
  module: ".torch"
  name: "StepLR"
  args:
    step_size: 1
    gamma: 0.1
