##
##
##

wandb:
  project: "sgg"
  entity: "visgator"
  save: false
  enabled: false
dataset:
  module: ".refcocog"
  path: "./data/refcocog"
  split_provider: "umd"
  generation:
    start: 0
    end: 2
    parser:
      module: ".llm"
      model: "tiiuae/falcon-7b-instruct"
      batch_size: 2
      prompt: "config/prompt.txt"
model:
  module: ".sgg"
  hidden_dim: 8
  encoders:
    model: "ViT-B-32" # default
    pretrained: "laion2b_s34b_b79k" # default
  detector:
    weights: "weights/groundingdino_swinb_cogcoor.pth"
    config: "config/GroundingDINO_SwinB_cfg.py"
    box_threshold: 0.25 # default
    text_threshold: 0.25 # default
  decoder:
    num_layers: 3
    num_heads: 8 # default
    epsilon_layer_scale: 0.1 # default
    dropout: 0.1 # default
  head:
    dropout: 0.1
  criterion:
    l1_weight: 1.0
    giou_weight: 1.0
    info_nce_weight: 0.1
seed: 3407
compile: False
num_epochs: 24
train_batch_size: 1
eval_batch_size: 1
eval_interval: 4
mixed_precision: true
# max_grad_norm: 10.0
optimizer:
  module: ".torch"
  name: "AdamW"
  args:
    lr: 0.001
lr_scheduler:
  module: ".torch"
  name: "OneCycleLR"
  args:
    max_lr: 0.001
